Repository engine-buddies/light-vox-engine, pull requests merged in 2018-10, with the labels that each got.

#9 Separate the Entity Components to a separate header
  Light Vox Engine/EntityComponents.h
  Light Vox Engine/EntityManager.h
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
Labels: P0, Tools

#8 CBV support - we have a camera now
  Assets/Models/voxel.obj
  Light Vox Engine/Camera.cpp
  Light Vox Engine/Engine.cpp
  Light Vox Engine/Engine.h
  Light Vox Engine/FrameResource.cpp
  Light Vox Engine/FrameResource.h
  Light Vox Engine/GraphicsCore.cpp
  Light Vox Engine/GraphicsCore.h
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
  Light Vox Engine/ObjLoader.cpp
  Light Vox Engine/ObjLoader.h
  Light Vox Engine/Shaders/ps_basic.hlsl
  Light Vox Engine/Shaders/vs_basic.hlsl
Labels: Graphics, P1

#14 Development Release Build Hotfix
  Light Vox Engine/DXSampleHelper.h
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/stdafx.h
Labels: P0, bug

#10 Instanced Rendering
  Light Vox Engine/Configs.h
  Light Vox Engine/Engine.cpp
  Light Vox Engine/Engine.h
  Light Vox Engine/FrameResource.cpp
  Light Vox Engine/FrameResource.h
  Light Vox Engine/GraphicsCore.cpp
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
  Light Vox Engine/ObjLoader.h
  Light Vox Engine/ShaderDefinitions.h
  Light Vox Engine/Shaders/ps_basic.hlsl
  Light Vox Engine/Shaders/vs_basic.hlsl
  Light Vox Engine/main.cpp
  Light Vox Engine/stdafx.h
Labels: Graphics, P1

#21 Job System Implementation
  Light Vox Engine/ConcurrentQueue.h
  Light Vox Engine/CpuJob.h
  Light Vox Engine/Engine.cpp
  Light Vox Engine/Engine.h
  Light Vox Engine/JobManager.cpp
  Light Vox Engine/JobManager.h
  Light Vox Engine/JobSequence.cpp
  Light Vox Engine/JobSequence.h
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
Labels: feature

#22 ECS and Physics
  Light Vox Engine/ComponentManager.cpp
  Light Vox Engine/ComponentManager.h
  Light Vox Engine/Configs.h
  Light Vox Engine/Engine.cpp
  Light Vox Engine/Engine.h
  Light Vox Engine/Entity.h
  Light Vox Engine/EntityComponents.h
  Light Vox Engine/EntityManager.cpp
  Light Vox Engine/EntityManager.h
  Light Vox Engine/GameTime.cpp
  Light Vox Engine/GameTime.h
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
  Light Vox Engine/Physics.cpp
  Light Vox Engine/Physics.h
  Light Vox Engine/packages.config
  Light Vox Engine/stdafx.h
Labels: P1, feature

#25 Unit Testing Framework
  Light Vox Engine.sln
  Light Vox Engine/Engine.cpp
  Light Vox Engine/JobSystem/CpuJob.h
  LightVox_UnitTests/ConcurrentQueueTests.cpp
  LightVox_UnitTests/LightVox_UnitTests.vcxproj
  LightVox_UnitTests/LightVox_UnitTests.vcxproj.filters
  LightVox_UnitTests/packages.config
  LightVox_UnitTests/stdafx.h
  LightVox_UnitTests/targetver.h
  unitTesting.md
Labels: P1, Tools, feature

#27 Update to job system to support member functions
  Light Vox Engine/JobSystem/CpuJob.h
  Light Vox Engine/JobSystem/JobManager.cpp
  Light Vox Engine/JobSystem/JobManager.h
  Light Vox Engine/JobSystem/JobSequence.cpp
Labels: P1, Tools, feature

#30 Cleaned up physics and created rigidbody class
  Light Vox Engine/ECS/ComponentManager.cpp
  Light Vox Engine/ECS/ComponentManager.h
  Light Vox Engine/ECS/Entity.h
  Light Vox Engine/ECS/EntityManager.cpp
  Light Vox Engine/ECS/EntityManager.h
  Light Vox Engine/Engine.cpp
  Light Vox Engine/Engine.h
  Light Vox Engine/Graphics/GraphicsCore.cpp
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
  Light Vox Engine/Physics/Physics.h
  Light Vox Engine/Physics/RigidBody.cpp
  Light Vox Engine/Physics/RigidBody.h
  Light Vox Engine/Physics/Solver.cpp
  Light Vox Engine/Physics/Solver.h
  Light Vox Engine/Utils/Configs.h
  Light Vox Engine/main.cpp
  Light Vox Engine/stdafx.h
Labels: P1, Physics

#32 Deferred Rendering
  Light Vox Engine/Engine.cpp
  Light Vox Engine/Engine.h
  Light Vox Engine/Graphics/Camera.cpp
  Light Vox Engine/Graphics/Camera.h
  Light Vox Engine/Graphics/FrameResource.cpp
  Light Vox Engine/Graphics/FrameResource.h
  Light Vox Engine/Graphics/GraphicsBase.cpp
  Light Vox Engine/Graphics/GraphicsCore.cpp
  Light Vox Engine/Graphics/GraphicsCore.h
  Light Vox Engine/Graphics/ObjLoader.cpp
  Light Vox Engine/Graphics/ObjLoader.h
  Light Vox Engine/Graphics/ShaderDefinitions.h
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
  Light Vox Engine/Physics/Solver.cpp
  Light Vox Engine/Shaders/ps_basic.hlsl
  Light Vox Engine/Shaders/ps_lighting.hlsl
  Light Vox Engine/Shaders/vs_FSQ.hlsl
  Light Vox Engine/Shaders/vs_basic.hlsl
  Light Vox Engine/Utils/Configs.h
  Light Vox Engine/Utils/DXSampleHelper.h
  Light Vox Engine/Utils/LVutils.h
Labels: Graphics, P0, feature

#33 Debugging stack - wireframe rendering for cubes
  Light Vox Engine/Engine.cpp
  Light Vox Engine/Engine.h
  Light Vox Engine/Graphics/DebugRenderer.cpp
  Light Vox Engine/Graphics/DebugRenderer.h
  Light Vox Engine/Graphics/FrameResource.cpp
  Light Vox Engine/Graphics/FrameResource.h
  Light Vox Engine/Graphics/GraphicsCore.cpp
  Light Vox Engine/Graphics/GraphicsCore.h
  Light Vox Engine/Graphics/ShaderDefinitions.h
  Light Vox Engine/Light Vox Engine.vcxproj
  Light Vox Engine/Light Vox Engine.vcxproj.filters
  Light Vox Engine/Shaders/ps_debug.hlsl
  Light Vox Engine/Shaders/vs_FSQ.hlsl
  Light Vox Engine/Shaders/vs_debug.hlsl
  Light Vox Engine/packages.config
Labels: Graphics
